name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Clone the Repo
      - uses: actions/checkout@v2
      # Get requirements
      - name: Install Dependencies
        run: python3 -m pip install -r requirements.txt
        shell: sh
      # Build
      - name: Build the results
        run: python3 main.py
        shell: sh
      # Publish Results
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
